### ISSUE TITLE
Scanning with Snipping Tool not working

### ISSUE THREAD

**Issue by ottozumkeller** [MarkHopper24/barcodrod.io#11]
When I try to scan a QR code using the Snipping Tool, the app closes (as far as I can see, it's supposed to), but the Snipping Tool doesn't open afterwards.

**Comment by MarkHopper24** [comment]
Hi @ottozumkeller, can you confirm what Windows build you're on? I'm only able to repro this on W11 Insiders Build 25300. Check the known issue here: https://blogs.windows.com/windows-insider/2023/02/15/announcing-windows-11-insider-preview-build-25300/

_[NEW] We’re investigating reports that the New button in Snipping Tool isn’t working for some Insiders after upgrading to Build 25295. If you are impacted by this, going to Settings > Apps > Default apps, and setting screen snipping as the default for ms-screenclip, it should resolve the issue._

Good test would be launching Snipping Tool, and seeing if clicking the '+ New' button. If nothing happens, likely the same issue.

**Comment by ottozumkeller** [comment]
Ah, yes I have Windows Insider build 25309, good to know this is a Windows bug. I must have overlooked it in the announcements. I guess I'll have to wait for Microsoft in that case. Thanks for the hint. Barcodrod.io really has everything I need.

**Comment by MarkHopper24** [comment]
@ottozumkeller Thanks for confirming! I'll try to add more checks in the next update so at the very least, barcodrod.io recovers more gracefully if this happens and reopens itself.
