### ISSUE TITLE
Bulk Decode - No Image Files Detected (they're there!)

### ISSUE THREAD

**Issue by jpooley-hearst** [MarkHopper24/barcodrod.io#15]
#14 is fixed and I can now browse and select the folder I would like to process, but the program reports "No image files detected in the selected folder.". If I try to process a single image file it successfully opens images in the folder. I have tried taking the files out of OneDrive but that did not help.

**Comment by MarkHopper24** [comment]
What is the format of the image files? Can you try a folder with a few pngs or jpegs to validate that works as expected?

Images stored in OneDrive should work, but they must be downloaded locally on the device (green check in file explorer vs white check).

**Comment by jpooley-hearst** [comment]
Hey they're JPG, HEIC, and PNG. I'm happy to use ImageMagick to convert to whatever format. But when I use the single image file tool in the application on a file in the folder it works, so I don't think format is the issue. I did also try locally downloading the files in OneDrive before I put them in a folder outside of OneDrive.

**Comment by MarkHopper24** [comment]
I believe I found the issue. Bulk decode is currently designed to filter out any files in a folder whose extensions do not end with .jpg, .png, .bmp, .gif, .heif, .hiec, .bmp, or .jpeg. Unfortunately, it doesn't account for case sensitivity so .PNG, .JPG, .Jpeg, etc. will be filtered out.

You should be able to use [PowerRename](https://learn.microsoft.com/en-us/windows/powertoys/powerrename) in PowerToys or similar tool to adjust the case sensitivity of the file extensions in bulk as a workaround in the meantime, but I'll need to get another patch out to address this. Again, really appreciate your patience and willingness to report these issues @jpooley-hearst. Will keep this issue updated when the next patch is released, hopefully within the next few days.

**Comment by MarkHopper24** [comment]
Resolved in [v1.4.2](https://github.com/MarkHopper24/barcodrod.io/releases/tag/v1.4.2) which is now published on the Microsoft Store and GitHub. 

@jpooley-hearst FYI
