### ISSUE TITLE
Aztec code creation not working

### ISSUE THREAD

**Issue by NatCounter** [MarkHopper24/barcodrod.io#16]
Hello!  I came across your app recently.  It is quite helpful and has been working well for me to scan QR codes from websites that want me to use an authenticator app for 2 factor.

I was playing around with creating qr codes because it seemed interesting, and I wanted to see what each of them looked like.  I failed to create an AZTEC code, resulting in the following error:

![Screenshot 2023-08-02 162401](https://github.com/MarkHopper24/barcodrod.io/assets/40151157/f96875ec-c4d7-4b73-a38e-5c03c6160ac7)

System:

HP Victus Laptop/Ryzen 7 5800H
Windows 11 Home (x64) 22H2
Build 22621.1992

If there is any additional information you may need, let me know.
Thanks for all the work that you've done on this app!

**Comment by MarkHopper24** [comment]
Thanks for reporting this issue, fix identified and will make it into the next patch.

**Comment by MarkHopper24** [comment]
This issue is fixed in v1.6 which has been submitted to the Microsoft Store. I expect it to arrive within the next few days.

Thanks for reporting @CircleShift! Please re-open if you see the issue still occur.
