### ISSUE TITLE
Barcodes export with black bar on the top

### ISSUE THREAD

**Issue by MikeLBN** [MarkHopper24/barcodrod.io#18]
Preview within app looks correct, exported to image has black bar on the top
![112023 0036 CODE_128](https://github.com/MarkHopper24/barcodrod.io/assets/1658841/79049da9-564f-485b-a5de-a156b0811e4e)
![112023 0039 QR_CODE](https://github.com/MarkHopper24/barcodrod.io/assets/1658841/50299c12-0b6c-4e4f-83a9-fa8f0ba66898)
![112023 0039 CODE_39](https://github.com/MarkHopper24/barcodrod.io/assets/1658841/0f029a5f-ebe8-4bbc-832a-f9b4eda2b36e)

**Comment by MarkHopper24** [comment]
Thanks for the report @lysylbn. Fixed in v1.8 which has been submitted to the Microsoft Store and should be released within the next few days. Please re-open if you're still seeing the same issue after updating.
