### ISSUE TITLE
New feature - opening storage localization in browser

### ISSUE THREAD

**Issue by Nandu334** [MarkHopper24/barcodrod.io#21]
Hi @MarkHopper24 ,

I've downloaded your QR code scanner app and it works fine but I've got a question about possible new feature.
I'd like to scan QR codes with a URL to a shared storage. Wanted to create a QR with, for example **file://xyz/123/** which upon scanning would be opened in a browser similar to a http://  from QR code. Chrome is capable of browsing storages so I'm just missing the point to automatically open it after scanning QR code with the link to the folder without having to copy the link and pasting it.

Do you think that would be possible to add?
I'm looking forward to your response 

Best regards,
Mateusz

**Comment by MarkHopper24** [comment]
@Nandu334 

Hey Mateusz, thanks for reaching out. Unfortunately file:// is a reserved URI scheme: 
https://learn.microsoft.com/en-us/windows/uwp/launch-resume/reserved-uri-scheme-names#reserved-uri-scheme-names

For that reason, Windows does not allow Chrome (or any other browser) to register itself to launch/access a file using that scheme by default. However, if your path contains an accessible file that has a registered app type to open it, the file:// scheme should work. For example:

file://xyz/123/ would not work as it's a path:
![image](https://github.com/MarkHopper24/barcodrod.io/assets/106134632/e3903e9e-c125-46be-b755-a0447c7fde90)


file://xyz/123/abc.json should work as long as it's an accessible file, and you have applications registered to open .json files:
![image](https://github.com/MarkHopper24/barcodrod.io/assets/106134632/724e6aa6-b40b-4b3b-91cf-b098265bc8d1)


But there's no way to launch a browser and point it to a file:// URI scheme on launch unfortunately. Closing this item for now but will reevaluate if both Windows and Chrome support this scenario in the future.
