### ISSUE TITLE
Thanks for the App!

### ISSUE THREAD

**Issue by ryanbarillosofficial** [MarkHopper24/barcodrod.io#23]

**Comment by ryanbarillosofficial** [comment]
Just saw this app while searching for an open-source QR scanner/generator on Windows (since lots of the OSS QR apps on Linux are not available on Windows), and I'm glad to land on this one.

I hope this continues maintenance for a long time, and that your code (especially in every new update) will be simple to maintain for you :)

**Comment by MarkHopper24** [comment]
Thanks @ryanbarillos! Appreciate the kind words.
