### ISSUE TITLE
Interface should Hide when Activating Snipping Tool

### ISSUE THREAD

**Issue by Suleman-Elahi** [MarkHopper24/barcodrod.io#7]
![Screenshot (352)](https://user-images.githubusercontent.com/24384996/210542829-9ce9d404-ff69-450b-afa3-114953eac3d3.png)

Right now, the UI of the tools stays active when clicking on the Snipping Tool button. Ideally, it should hid itself or minimized so a user can easily select the QR code on the screen.

**Comment by MarkHopper24** [comment]
This is a great idea, thanks for the feedback @Suleman-Elahi. Will aim to include this in the next update.

**Comment by MarkHopper24** [comment]
This feature is available with v1.1 which is now available on GitHub and is in the process of being published to the Microsoft Store. Please feel free to re-open if it doesn't work as expected.
