### ISSUE TITLE
Support for DirectShow webcams

### ISSUE THREAD

**Issue by rollingmoai** [MarkHopper24/barcodrod.io#8]
I don't have a camera. I only use a GoPro webcam and virtual webcams such as the OBS virtual webcam. However, barcodrod doesn't seem to detect it and I assume it doesn't support DirectShow webcams. Please add support for it!

Additionally, a drop-down menu to select the available webcam is a must, thanks!

**Comment by cmdshft** [comment]
Seconding this. I have a DSLR that I use as a webcam and for streaming/Teams. Would love to have the option to use this.

**Comment by MarkHopper24** [comment]
Thanks for the feedback @rollingmoai @cmdshft  I'm not very familiar with DirectShow, but  can start investigating this in the next week or two. If it's possible, will look to include it in v1.4.

**Comment by Mahopper** [comment]
@rollingmoai @cmdshft Starting investigation on this over the weekend. Going to start with a prompt/dropdown when multiple webcams are detected, and then start looking into DirectShow. 

I don't have a GoPro for testing, but just to confirm- OBS's virtual cameras leverage DirectShow? Any other good ways to test a DirectShow camera come to mind that I might be missing? Thanks!

**Comment by MarkHopper24** [comment]
@rollingmoai @cmdshft Starting investigation on this over the weekend. Going to start with a prompt/dropdown when multiple webcams are detected, and then start looking into DirectShow. 

I don't have a GoPro for testing, but just to confirm- OBS's virtual cameras leverage DirectShow? Any other good ways to test a DirectShow camera come to mind that I might be missing? Thanks!

**Comment by rollingmoai** [comment]
> OBS's virtual cameras leverage DirectShow

Yep, you can test that one out.

**Comment by MarkHopper24** [comment]
After some research, it looks like the official DirectShow APIs are dated only available through native C++ and are not easily available in .NET/C#. The most promising option I've found seems to be a 3rd party library such as directshow.net, but I'll need to do more investigation to see how feasible this would be to implement.

That being said, I did completely rework the existing webcam functionality to use the default Windows Camera app in v1.4. This removes a lot of general bugginess and enables extended functionality from the Windows Camera app including: 
	- Cycling through detected webcams (If Windows/Windows Camera app detects your device, it should be usable in barcodrod.io).
	- Toggling HDR 
	- Auto-enhancing captured photos before decoding using the "Document" feature
	- Retaking a photo before attempting to decode it
	- Rotating a captured photo

Updated source is now live, and I'd expect the v1.4 package to be available on the Microsoft Store and here on GitHub within the next day or so.

I do want to add support for DirectStream in the future, but it wasn't a trivial amount of work unfortunately and won't make it in the v1.4 release. I'll keep this thread updated as things progress but for now, marking as 'under investigation'. 

@cmdshft @rollingmoai FYI

**Comment by MarkHopper24** [comment]
I’ve finally gotten around to digging into this and have made some good progress. I have a prototype build that supports DirectShow devices + the ability to switch between different capture sources. I have tested with 2 webcams and OBS so far, and the results seem promising. Just need to work through a few bugs.

I plan on including DirectShow support as an experimental feature in the next release- Hopefully within the next week or two at the latest.

@rollingmoai @cmdshft, this wasn’t an area I was very familiar with so would love to hear your feedback once it ships. Will keep this post updated as things progress.

**Comment by cmdshft** [comment]
Definitely! Ping me when it's ready to test and I will let you know.

**Comment by MarkHopper24** [comment]
@cmdshft @rollingmoai 

Support for DirectShow sources will be included in v1.5 which has been submitted to the Microsoft Store. I expect it to arrive early next week. Closing this item out for now, but please feel free to file new issues if you run into any problems. Thanks for the feedback (and patience) on this one!
